version: '3'

services:
  firestore-go:
    build: .
    command: /app/firestore-go
    #image: websocket-service:v1.0.0
    volumes:
      - ./credentials/PRIVATE.json:/tmp/keys/PRIVATE.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/PRIVATE.json
      - GCP_PROJECT_ID=chargerevolutioncloud
      # LOG_LEVEL Panic, Fatal, Error, Warn, Info, Debug, Trace
      - LOG_LEVEL=Info